package fr.regemrp.mod.common.init;

import fr.regemrp.mod.Main;
import fr.regemrp.mod.common.blocks.BlockBase;
import fr.regemrp.mod.common.blocks.dynamx.BaseDynamxBlock;
import fr.regemrp.mod.common.utils.References;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraft.util.ResourceLocation;

import java.util.ArrayList;
import java.util.List;

public class AllRegister {

    public static List<Item> ITEMS = new ArrayList<Item>();
    public static List<Block> BLOCKS = new ArrayList<Block>();

    /* Item & Block Register */

    public static BlockBase ASPHALT = new BlockBase("asphalt", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_ANGLE_LINE_LEFT = new BlockBase("asphalt_angle_line_left", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_ANGLE_LINE_RIGHT = new BlockBase("asphalt_angle_line_right", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_ARROW = new BlockBase("asphalt_arrow", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_BIG_LINE = new BlockBase("asphalt_big_line", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_BIG_LINE_GROW_RIGHT = new BlockBase("asphalt_big_line_grow_right", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_BIG_LINE_HALF = new BlockBase("asphalt_big_line_half", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_BIG_LINE_SEPARATE_BOTH = new BlockBase("asphalt_big_line_separate_both", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_BIG_LINE_SEPARATE_LEFT = new BlockBase("asphalt_big_line_separate_left", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_BIG_LINE_SEPARATE_RIGHT = new BlockBase("asphalt_big_line_separate_right", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_BIG_LINE_T = new BlockBase("asphalt_big_line_t", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_BIG_LINE_TRANSFORM_LEFT = new BlockBase("asphalt_big_line_transform_left", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_BIG_LINE_TRANSFORM_RIGHT = new BlockBase("asphalt_big_line_transform_right", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_BIG_LINE_TURN = new BlockBase("asphalt_big_line_turn", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_BIG_LINE_TURN2 = new BlockBase("asphalt_big_line_turn2", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_BIG_LINE_X = new BlockBase("asphalt_big_line_x", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_BIG_T__NORMAL_LINE = new BlockBase("asphalt_big_t__normal_line", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_CENTER_ANGLE_LINE = new BlockBase("asphalt_center_angle_line", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_CENTER_DOUBLE_LINE_CROSS_INTERSECTION = new BlockBase("asphalt_center_double_line_cross_intersection", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_CENTER_DOUBLE_LINE_INTERSECTION_BIG_LINE = new BlockBase("asphalt_center_double_line_intersection_big_line", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_CENTER_DOUBLE_LINE_INTERSECTION_BIG_LINE_LEFT = new BlockBase("asphalt_center_double_line_intersection_big_line_left", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_CENTER_DOUBLE_LINE_INTERSECTION_BIG_LINE_RIGHT = new BlockBase("asphalt_center_double_line_intersection_big_line_right", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_CENTER_LINE_INTERSECTION_LEFT = new BlockBase("asphalt_center_line_intersection_left", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_CENTER_LINE_INTERSECTION_RIGHT = new BlockBase("asphalt_center_line_intersection_right", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_CENTER_LINE_T_INTERSECTION = new BlockBase("asphalt_center_line_t_intersection", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_CENTER_TURNING_LINE = new BlockBase("asphalt_center_turning_line", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_CROSS_LINE = new BlockBase("asphalt_cross_line", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_CUT_ARROW = new BlockBase("asphalt_cut_arrow", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_CUT_ARROW_TOP = new BlockBase("asphalt_cut_arrow_top", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_ANGLE_LINE = new BlockBase("asphalt_double_angle_line", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_ARROW = new BlockBase("asphalt_double_arrow", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE = new BlockBase("asphalt_double_line", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_CONNECT_DASHED = new BlockBase("asphalt_double_line_connect_dashed", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_DASHED = new BlockBase("asphalt_double_line_dashed", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_DOUBLE_SEPARATE_BOTH = new BlockBase("asphalt_double_line_double_separate_both", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_DOUBLE_SEPARATE_BOTH_BOTTOM = new BlockBase("asphalt_double_line_double_separate_both_bottom", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_DOUBLE_SEPARATE_BOTH_TOP = new BlockBase("asphalt_double_line_double_separate_both_top", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_DOUBLE_SEPARATE_LEFT = new BlockBase("asphalt_double_line_double_separate_left", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_DOUBLE_SEPARATE_LEFT_BOTTOM = new BlockBase("asphalt_double_line_double_separate_left_bottom", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_DOUBLE_SEPARATE_LEFT_TOP = new BlockBase("asphalt_double_line_double_separate_left_top", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_DOUBLE_SEPARATE_RIGHT = new BlockBase("asphalt_double_line_double_separate_right", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_DOUBLE_SEPARATE_RIGHTTOP = new BlockBase("asphalt_double_line_double_separate_righttop", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_DOUBLE_SEPARATE_RIGHT_BOTTOM = new BlockBase("asphalt_double_line_double_separate_right_bottom", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_HALF = new BlockBase("asphalt_double_line_half", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_INTERSECTION_BOTH_LINE_SEPARATE = new BlockBase("asphalt_double_line_intersection_both_line_separate", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_INTERSECTION_RIGHT_DOUBLE_LINE = new BlockBase("asphalt_double_line_intersection_right_double_line", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_INTERSECTION_RIGHT_LINE2 = new BlockBase("asphalt_double_line_intersection_right_line-1", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_INTERSECTION_RIGHT_LINE = new BlockBase("asphalt_double_line_intersection_right_line", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_LEFT_TRANSFORM_LEFT = new BlockBase("asphalt_double_line_left_transform_left", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_LEFT_TURN_SIDE_LINE_CONTINUE = new BlockBase("asphalt_double_line_left_turn_side_line_continue", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_LEFT_TURN_SIDE_LINE_CONTINUE2 = new BlockBase("asphalt_double_line_left_turn_side_line_continue2", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_MERGE_LEFT_INTERSECTION = new BlockBase("asphalt_double_line_merge_left_intersection", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_MERGE_LINE_LEFT = new BlockBase("asphalt_double_line_merge_line_left", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_MERGE_LINE_RIGHT = new BlockBase("asphalt_double_line_merge_line_right", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_MERGE_RIGHT_INTERSECTION = new BlockBase("asphalt_double_line_merge_right_intersection", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_RIGHT_TRANSFORM_RIGHT = new BlockBase("asphalt_double_line_right_transform_right", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_RIGHT_TURN_SIDE_LINE_CONTINUE = new BlockBase("asphalt_double_line_right_turn_side_line_continue", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_RIGHT_TURN_SIDE_LINE_CONTINUE2 = new BlockBase("asphalt_double_line_right_turn_side_line_continue2", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_SEPARATE_HALF_JOIN_BOTTOM = new BlockBase("asphalt_double_line_separate_half_join_bottom", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_SEPARE_LEFT_TURN = new BlockBase("asphalt_double_line_separe_left_turn", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_SEPARE_ONE_LINE_BOTH_SIDES = new BlockBase("asphalt_double_line_separe_one_line_both_sides", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_SEPARE_ONE_LINE_BOTH_SIDES2 = new BlockBase("asphalt_double_line_separe_one_line_both_sides2", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_SEPARE_RIGHT_TURN = new BlockBase("asphalt_double_line_separe_right_turn", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_TRANSFORM_LEFT = new BlockBase("asphalt_double_line_transform_left", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_TRANSFORM_RIGHT = new BlockBase("asphalt_double_line_transform_right", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_TURN = new BlockBase("asphalt_double_line_turn", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_TURN2 = new BlockBase("asphalt_double_line_turn2", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_DOUBLE_LINE_X_INTERSECTION = new BlockBase("asphalt_double_line_x_intersection", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_INTERSECTION_BLOCK_LEFT = new BlockBase("asphalt_intersection_block_left", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_INTERSECTION_BLOCK_RIGHT = new BlockBase("asphalt_intersection_block_right", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_INTERSECTION_LINE_BIG_LINE = new BlockBase("asphalt_intersection_line_big_line", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_INTERSECTION_T_DOUBLED_LINE = new BlockBase("asphalt_intersection_t_doubled_line", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_INTERSECTION_T_DOUBLE_LINE2 = new BlockBase("asphalt_intersection_t_double_line2", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_INTERSECTION_T_DOUBLE_LINE_SEPARATE = new BlockBase("asphalt_intersection_t_double_line_separate", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_INTERSECTION_T_DOUBLE_LINE_SEPARATE_C_C = new BlockBase("asphalt_intersection_t_double_line_separate_c_c", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_INTERSECTION_T_LINE_BIG_LINE = new BlockBase("asphalt_intersection_t_line_big_line", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_INTERSECTION_V = new BlockBase("asphalt_intersection_v", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_INTERSECTION_X_DOUBLE_LINE_SEPARATE = new BlockBase("asphalt_intersection_x_double_line_separate", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_A = new BlockBase("asphalt_letter_a", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_B = new BlockBase("asphalt_letter_b", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_C = new BlockBase("asphalt_letter_c", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_D = new BlockBase("asphalt_letter_d", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_E = new BlockBase("asphalt_letter_e", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_F = new BlockBase("asphalt_letter_f", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_G = new BlockBase("asphalt_letter_g", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_H = new BlockBase("asphalt_letter_h", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_I = new BlockBase("asphalt_letter_i", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_J = new BlockBase("asphalt_letter_j", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_K = new BlockBase("asphalt_letter_k", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_L = new BlockBase("asphalt_letter_l", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_M = new BlockBase("asphalt_letter_m", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_N = new BlockBase("asphalt_letter_n", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_O = new BlockBase("asphalt_letter_o", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_P = new BlockBase("asphalt_letter_p", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_Q = new BlockBase("asphalt_letter_q", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_R = new BlockBase("asphalt_letter_r", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_S = new BlockBase("asphalt_letter_s", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_T = new BlockBase("asphalt_letter_t", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_U = new BlockBase("asphalt_letter_u", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_V = new BlockBase("asphalt_letter_v", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_W = new BlockBase("asphalt_letter_w", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_X = new BlockBase("asphalt_letter_x", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_Y = new BlockBase("asphalt_letter_y", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LETTER_Z = new BlockBase("asphalt_letter_z", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE = new BlockBase("asphalt_line", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_CONE = new BlockBase("asphalt_line_cone", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_DASHED = new BlockBase("asphalt_line_dashed", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_DOUBLE_SECOND_BOTH_DASHED = new BlockBase("asphalt_line_double_second_both_dashed", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_DOUBLE_SECOND_LEFT_DASHED = new BlockBase("asphalt_line_double_second_left_dashed", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_DOUBLE_SECOND_RIGHT_DASHED = new BlockBase("asphalt_line_double_second_right_dashed", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_GROW_BOTH2 = new BlockBase("asphalt_line_grow_both2", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_GROW_LEFT = new BlockBase("asphalt_line_grow_left", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_GROW_LEFT2 = new BlockBase("asphalt_line_grow_left2", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_GROW_RIGHT = new BlockBase("asphalt_line_grow_right", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_GROW_RIGHT2 = new BlockBase("asphalt_line_grow_right2", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_INTERSECTION_DOUBLE_LINES = new BlockBase("asphalt_line_intersection_double_lines", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_SEPARATE_LEFT3 = new BlockBase("asphalt_line_separate_left3", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_SEPARATE_LEFT4 = new BlockBase("asphalt_line_separate_left4", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_SEPARATE_RIGHT3 = new BlockBase("asphalt_line_separate_right3", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_SEPARATE_RIGHT4 = new BlockBase("asphalt_line_separate_right4", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_SEPARE_LEFT2 = new BlockBase("asphalt_line_separe_left2", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_SEPARE_RIGHT = new BlockBase("asphalt_line_separe_right", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_SEPARE_TZ = new BlockBase("asphalt_line_separe_tz", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_SEPARE_Y = new BlockBase("asphalt_line_separe_y", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_SEPARE_Z = new BlockBase("asphalt_line_separe_z", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_SEPARE_Z2 = new BlockBase("asphalt_line_separe_z2", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_SEPARE_ZT = new BlockBase("asphalt_line_separe_zt", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_TRANSFORM_SITE = new BlockBase("asphalt_line_transform_site", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_TURN_WITH_SECURITY_LINES_LEFT = new BlockBase("asphalt_line_turn_with_security_lines_left", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_TURN_WITH_SECURITY_LINES_RIGHT = new BlockBase("asphalt_line_turn_with_security_lines_right", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_WITH_GROW_LEFT = new BlockBase("asphalt_line_with_grow_left", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_WITH_GROW_RIGHT = new BlockBase("asphalt_line_with_grow_right", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_WITH_SECURITY_LINES_DOWN = new BlockBase("asphalt_line_with_security_lines_down", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_WITH_SECURITY_LINES_LEFT_REDUCE = new BlockBase("asphalt_line_with_security_lines_left_reduce", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_WITH_SECURITY_LINES_LEFT_REDUCE2 = new BlockBase("asphalt_line_with_security_lines_left_reduce2", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_WITH_SECURITY_LINES_RIGHT_REDUCE = new BlockBase("asphalt_line_with_security_lines_right_reduce", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_WITH_SECURITY_LINES_RIGHT_REDUCE2 = new BlockBase("asphalt_line_with_security_lines_right_reduce2", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_LINE_WITH_SECURITY_LINES_UP = new BlockBase("asphalt_line_with_security_lines_up", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_MEDIUM_LINE_CROSS = new BlockBase("asphalt_medium_line_cross", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_NUMBER_0 = new BlockBase("asphalt_number_0", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_NUMBER_1 = new BlockBase("asphalt_number_1", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_NUMBER_2 = new BlockBase("asphalt_number_2", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_NUMBER_3 = new BlockBase("asphalt_number_3", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_NUMBER_4 = new BlockBase("asphalt_number_4", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_NUMBER_5 = new BlockBase("asphalt_number_5", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_NUMBER_6 = new BlockBase("asphalt_number_6", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_NUMBER_7 = new BlockBase("asphalt_number_7", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_NUMBER_8 = new BlockBase("asphalt_number_8", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_NUMBER_9 = new BlockBase("asphalt_number_9", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_POINT_CUT_ARROW = new BlockBase("asphalt_point_cut_arrow", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_SECURITY_LINES = new BlockBase("asphalt_security_lines", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_SIDE_LINE = new BlockBase("asphalt_side_line", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_SIDE_LINE_DASHED = new BlockBase("asphalt_side_line_dashed", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_SIDE_LINE_DASHED_CUT_BOTH = new BlockBase("asphalt_side_line_dashed_cut_both", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_SIDE_LINE_DASHED_CUT_LEFT = new BlockBase("asphalt_side_line_dashed_cut_left", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_SIDE_LINE_DASHED_CUT_RIGHT = new BlockBase("asphalt_side_line_dashed_cut_right", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_SIDE_LINE_HALF = new BlockBase("asphalt_side_line_half", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_SIDE_LINE_TURN4 = new BlockBase("asphalt_side_line_turn-1", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_SIDE_LINE_TURN = new BlockBase("asphalt_side_line_turn", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_SIDE_LINE_TURN3 = new BlockBase("asphalt_side_line_turn2-1", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_SIDE_LINE_TURN2 = new BlockBase("asphalt_side_line_turn2", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_SIDE_TRANSFORM_LINE = new BlockBase("asphalt_side_transform_line", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_SIDE_TRANSFORM_LINE2LEFT = new BlockBase("asphalt_side_transform_line2left", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_SIDE_TRANSFORM_LINE2RIGHT = new BlockBase("asphalt_side_transform_line2right", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_TURN_DOUBLE_LINE_MERGING = new BlockBase("asphalt_turn_double_line_merging", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_T_LINE = new BlockBase("asphalt_t_line", Material.ROCK, Main.roadTab, 1f, 1f);
    public static BlockBase ASPHALT_GRAY = new BlockBase("asphalt_gray", Material.ROCK, Main.roadTab, 1f, 1f);


    /* Dyanmx Register */

    public static BaseDynamxBlock test;

    public static void dynamxInit(){
        test = new BaseDynamxBlock(Material.ROCK, References.MODID, "test", new ResourceLocation("regemrp","models/test/photocopieuse.obj"), Main.mainTab);
    }

}
